language: ruby
script: "script/test_all 2>&1"
bundler_args: "--standalone --binstubs"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - 2.1.2
  - ree
  - jruby-18mode
  - jruby
  - rbx
env:
  - RSPEC_BRANCH=master
  - RSPEC_BRANCH=2-99-maintenance

